#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentScanningLibrary.App_Code
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CimscoScanning")]
	public partial class ScanningDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertScannedRecord(ScannedRecord instance);
    partial void UpdateScannedRecord(ScannedRecord instance);
    partial void DeleteScannedRecord(ScannedRecord instance);
    #endregion
		
		public ScanningDataClassesDataContext() : 
				base(global::DocumentScanningLibrary.Properties.Settings.Default.CimscoScanningConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ScanningDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScanningDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScanningDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScanningDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ScannedRecord> ScannedRecords
		{
			get
			{
				return this.GetTable<ScannedRecord>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ScannedRecords")]
	public partial class ScannedRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _InvoiceNumber;
		
		private int _CustomerNumber;
		
		private string _CompanyName;
		
		private string _AccountNumber;
		
		private string _ICPnumber;
		
		private System.Nullable<decimal> _LCfixedUnits;
		
		private System.Nullable<decimal> _LCfixedCostPerUnit;
		
		private System.Nullable<decimal> _LCfixedCharge;
		
		private System.Nullable<decimal> _LCvariableUnits;
		
		private System.Nullable<decimal> _LCvariableCostPerUnit;
		
		private System.Nullable<decimal> _LCvariableCharge;
		
		private System.Nullable<decimal> _LCmaxDemandUnits;
		
		private System.Nullable<decimal> _LCmaxDemandCostPerUnit;
		
		private System.Nullable<decimal> _LCmaxDemandCharge;
		
		private System.Nullable<decimal> _LCassessedCapacityUnits;
		
		private System.Nullable<decimal> _LCassessedCapacityPerUnit;
		
		private System.Nullable<decimal> _LCassessedCapacityCharge;
		
		private System.Nullable<decimal> _Weekday00_04_Units;
		
		private System.Nullable<decimal> _Weekday04_08_Units;
		
		private System.Nullable<decimal> _Weekday08_12_Units;
		
		private System.Nullable<decimal> _Weekday12_16_Units;
		
		private System.Nullable<decimal> _Weekday16_20_Units;
		
		private System.Nullable<decimal> _Weekday20_24_Units;
		
		private System.Nullable<decimal> _Weekend00_04_Units;
		
		private System.Nullable<decimal> _Weekend04_08_Units;
		
		private System.Nullable<decimal> _Weekend08_12_Units;
		
		private System.Nullable<decimal> _Weekend12_16_Units;
		
		private System.Nullable<decimal> _Weekend16_20_Units;
		
		private System.Nullable<decimal> _Weekend20_24_Units;
		
		private System.Nullable<decimal> _Weekday00_04_Losses;
		
		private System.Nullable<decimal> _Weekday04_08_Losses;
		
		private System.Nullable<decimal> _Weekday08_12_Losses;
		
		private System.Nullable<decimal> _Weekday12_16_Losses;
		
		private System.Nullable<decimal> _Weekday16_20_Losses;
		
		private System.Nullable<decimal> _Weekday20_24_Losses;
		
		private System.Nullable<decimal> _Weekend00_04_Losses;
		
		private System.Nullable<decimal> _Weekend04_08_Losses;
		
		private System.Nullable<decimal> _Weekend08_12_Losses;
		
		private System.Nullable<decimal> _Weekend12_16_Losses;
		
		private System.Nullable<decimal> _Weekend16_20_Losses;
		
		private System.Nullable<decimal> _Weekend20_24_Losses;
		
		private System.Nullable<decimal> _Weekday00_04_CostPerUnit;
		
		private System.Nullable<decimal> _Weekday04_08_CostPerUnit;
		
		private System.Nullable<decimal> _Weekday08_12_CostPerUnit;
		
		private System.Nullable<decimal> _Weekday12_16_CostPerUnit;
		
		private System.Nullable<decimal> _Weekday16_20_CostPerUnit;
		
		private System.Nullable<decimal> _Weekday20_24_CostPerUnit;
		
		private System.Nullable<decimal> _Weekend00_04_CostPerUnit;
		
		private System.Nullable<decimal> _Weekend04_08_CostPerUnit;
		
		private System.Nullable<decimal> _Weekend08_12_CostPerUnit;
		
		private System.Nullable<decimal> _Weekend12_16_CostPerUnit;
		
		private System.Nullable<decimal> _Weekend16_20_CostPerUnit;
		
		private System.Nullable<decimal> _Weekend20_24_CostPerUnit;
		
		private System.Nullable<System.DateTime> _FromDate;
		
		private System.Nullable<System.DateTime> _ToDate;
		
		private System.Nullable<int> _FailedMatches;
		
		private string _ScannedFileName;
		
		private System.Nullable<System.DateTime> _ScanDate;
		
		private System.Nullable<int> _FailedValidations;
		
		private System.Nullable<decimal> _Weekday00_04_Charge;
		
		private System.Nullable<decimal> _Weekday04_08_Charge;
		
		private System.Nullable<decimal> _Weekday08_12_Charge;
		
		private System.Nullable<decimal> _Weekday12_16_Charge;
		
		private System.Nullable<decimal> _Weekday16_20_Charge;
		
		private System.Nullable<decimal> _Weekday20_24_Charge;
		
		private System.Nullable<decimal> _Weekend00_04_Charge;
		
		private System.Nullable<decimal> _Weekend04_08_Charge;
		
		private System.Nullable<decimal> _Weekend08_12_Charge;
		
		private System.Nullable<decimal> _Weekend12_16_Charge;
		
		private System.Nullable<decimal> _Weekend16_20_Charge;
		
		private System.Nullable<decimal> _Weekend20_24_Charge;
		
		private System.Nullable<decimal> _AdminCharge_Units;
		
		private System.Nullable<decimal> _AdminCharge_Rate;
		
		private System.Nullable<decimal> _AdminCharge_Charge;
		
		private System.Nullable<decimal> _ECLevies_Units;
		
		private System.Nullable<decimal> _ECLevies_Rate;
		
		private System.Nullable<decimal> _ECLevies_Charge;
		
		private System.Nullable<decimal> _TotalCharge;
		
		private string _FailedValidationRecords;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnInvoiceNumberChanging(string value);
    partial void OnInvoiceNumberChanged();
    partial void OnCustomerNumberChanging(int value);
    partial void OnCustomerNumberChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnICPnumberChanging(string value);
    partial void OnICPnumberChanged();
    partial void OnLCfixedUnitsChanging(System.Nullable<decimal> value);
    partial void OnLCfixedUnitsChanged();
    partial void OnLCfixedCostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnLCfixedCostPerUnitChanged();
    partial void OnLCfixedChargeChanging(System.Nullable<decimal> value);
    partial void OnLCfixedChargeChanged();
    partial void OnLCvariableUnitsChanging(System.Nullable<decimal> value);
    partial void OnLCvariableUnitsChanged();
    partial void OnLCvariableCostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnLCvariableCostPerUnitChanged();
    partial void OnLCvariableChargeChanging(System.Nullable<decimal> value);
    partial void OnLCvariableChargeChanged();
    partial void OnLCmaxDemandUnitsChanging(System.Nullable<decimal> value);
    partial void OnLCmaxDemandUnitsChanged();
    partial void OnLCmaxDemandCostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnLCmaxDemandCostPerUnitChanged();
    partial void OnLCmaxDemandChargeChanging(System.Nullable<decimal> value);
    partial void OnLCmaxDemandChargeChanged();
    partial void OnLCassessedCapacityUnitsChanging(System.Nullable<decimal> value);
    partial void OnLCassessedCapacityUnitsChanged();
    partial void OnLCassessedCapacityPerUnitChanging(System.Nullable<decimal> value);
    partial void OnLCassessedCapacityPerUnitChanged();
    partial void OnLCassessedCapacityChargeChanging(System.Nullable<decimal> value);
    partial void OnLCassessedCapacityChargeChanged();
    partial void OnWeekday00_04_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekday00_04_UnitsChanged();
    partial void OnWeekday04_08_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekday04_08_UnitsChanged();
    partial void OnWeekday08_12_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekday08_12_UnitsChanged();
    partial void OnWeekday12_16_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekday12_16_UnitsChanged();
    partial void OnWeekday16_20_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekday16_20_UnitsChanged();
    partial void OnWeekday20_24_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekday20_24_UnitsChanged();
    partial void OnWeekend00_04_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekend00_04_UnitsChanged();
    partial void OnWeekend04_08_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekend04_08_UnitsChanged();
    partial void OnWeekend08_12_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekend08_12_UnitsChanged();
    partial void OnWeekend12_16_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekend12_16_UnitsChanged();
    partial void OnWeekend16_20_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekend16_20_UnitsChanged();
    partial void OnWeekend20_24_UnitsChanging(System.Nullable<decimal> value);
    partial void OnWeekend20_24_UnitsChanged();
    partial void OnWeekday00_04_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekday00_04_LossesChanged();
    partial void OnWeekday04_08_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekday04_08_LossesChanged();
    partial void OnWeekday08_12_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekday08_12_LossesChanged();
    partial void OnWeekday12_16_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekday12_16_LossesChanged();
    partial void OnWeekday16_20_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekday16_20_LossesChanged();
    partial void OnWeekday20_24_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekday20_24_LossesChanged();
    partial void OnWeekend00_04_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekend00_04_LossesChanged();
    partial void OnWeekend04_08_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekend04_08_LossesChanged();
    partial void OnWeekend08_12_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekend08_12_LossesChanged();
    partial void OnWeekend12_16_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekend12_16_LossesChanged();
    partial void OnWeekend16_20_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekend16_20_LossesChanged();
    partial void OnWeekend20_24_LossesChanging(System.Nullable<decimal> value);
    partial void OnWeekend20_24_LossesChanged();
    partial void OnWeekday00_04_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekday00_04_CostPerUnitChanged();
    partial void OnWeekday04_08_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekday04_08_CostPerUnitChanged();
    partial void OnWeekday08_12_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekday08_12_CostPerUnitChanged();
    partial void OnWeekday12_16_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekday12_16_CostPerUnitChanged();
    partial void OnWeekday16_20_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekday16_20_CostPerUnitChanged();
    partial void OnWeekday20_24_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekday20_24_CostPerUnitChanged();
    partial void OnWeekend00_04_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekend00_04_CostPerUnitChanged();
    partial void OnWeekend04_08_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekend04_08_CostPerUnitChanged();
    partial void OnWeekend08_12_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekend08_12_CostPerUnitChanged();
    partial void OnWeekend12_16_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekend12_16_CostPerUnitChanged();
    partial void OnWeekend16_20_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekend16_20_CostPerUnitChanged();
    partial void OnWeekend20_24_CostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnWeekend20_24_CostPerUnitChanged();
    partial void OnFromDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFromDateChanged();
    partial void OnToDateChanging(System.Nullable<System.DateTime> value);
    partial void OnToDateChanged();
    partial void OnFailedMatchesChanging(System.Nullable<int> value);
    partial void OnFailedMatchesChanged();
    partial void OnScannedFileNameChanging(string value);
    partial void OnScannedFileNameChanged();
    partial void OnScanDateChanging(System.Nullable<System.DateTime> value);
    partial void OnScanDateChanged();
    partial void OnFailedValidationsChanging(System.Nullable<int> value);
    partial void OnFailedValidationsChanged();
    partial void OnWeekday00_04_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekday00_04_ChargeChanged();
    partial void OnWeekday04_08_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekday04_08_ChargeChanged();
    partial void OnWeekday08_12_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekday08_12_ChargeChanged();
    partial void OnWeekday12_16_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekday12_16_ChargeChanged();
    partial void OnWeekday16_20_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekday16_20_ChargeChanged();
    partial void OnWeekday20_24_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekday20_24_ChargeChanged();
    partial void OnWeekend00_04_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekend00_04_ChargeChanged();
    partial void OnWeekend04_08_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekend04_08_ChargeChanged();
    partial void OnWeekend08_12_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekend08_12_ChargeChanged();
    partial void OnWeekend12_16_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekend12_16_ChargeChanged();
    partial void OnWeekend16_20_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekend16_20_ChargeChanged();
    partial void OnWeekend20_24_ChargeChanging(System.Nullable<decimal> value);
    partial void OnWeekend20_24_ChargeChanged();
    partial void OnAdminCharge_UnitsChanging(System.Nullable<decimal> value);
    partial void OnAdminCharge_UnitsChanged();
    partial void OnAdminCharge_RateChanging(System.Nullable<decimal> value);
    partial void OnAdminCharge_RateChanged();
    partial void OnAdminCharge_ChargeChanging(System.Nullable<decimal> value);
    partial void OnAdminCharge_ChargeChanged();
    partial void OnECLevies_UnitsChanging(System.Nullable<decimal> value);
    partial void OnECLevies_UnitsChanged();
    partial void OnECLevies_RateChanging(System.Nullable<decimal> value);
    partial void OnECLevies_RateChanged();
    partial void OnECLevies_ChargeChanging(System.Nullable<decimal> value);
    partial void OnECLevies_ChargeChanged();
    partial void OnTotalChargeChanging(System.Nullable<decimal> value);
    partial void OnTotalChargeChanged();
    partial void OnFailedValidationRecordsChanging(string value);
    partial void OnFailedValidationRecordsChanged();
    #endregion
		
		public ScannedRecord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this.OnInvoiceNumberChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNumber = value;
					this.SendPropertyChanged("InvoiceNumber");
					this.OnInvoiceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNumber", DbType="Int NOT NULL")]
		public int CustomerNumber
		{
			get
			{
				return this._CustomerNumber;
			}
			set
			{
				if ((this._CustomerNumber != value))
				{
					this.OnCustomerNumberChanging(value);
					this.SendPropertyChanging();
					this._CustomerNumber = value;
					this.SendPropertyChanged("CustomerNumber");
					this.OnCustomerNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(30)")]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICPnumber", DbType="NVarChar(30)")]
		public string ICPnumber
		{
			get
			{
				return this._ICPnumber;
			}
			set
			{
				if ((this._ICPnumber != value))
				{
					this.OnICPnumberChanging(value);
					this.SendPropertyChanging();
					this._ICPnumber = value;
					this.SendPropertyChanged("ICPnumber");
					this.OnICPnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCfixedUnits", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCfixedUnits
		{
			get
			{
				return this._LCfixedUnits;
			}
			set
			{
				if ((this._LCfixedUnits != value))
				{
					this.OnLCfixedUnitsChanging(value);
					this.SendPropertyChanging();
					this._LCfixedUnits = value;
					this.SendPropertyChanged("LCfixedUnits");
					this.OnLCfixedUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCfixedCostPerUnit", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCfixedCostPerUnit
		{
			get
			{
				return this._LCfixedCostPerUnit;
			}
			set
			{
				if ((this._LCfixedCostPerUnit != value))
				{
					this.OnLCfixedCostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._LCfixedCostPerUnit = value;
					this.SendPropertyChanged("LCfixedCostPerUnit");
					this.OnLCfixedCostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCfixedCharge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCfixedCharge
		{
			get
			{
				return this._LCfixedCharge;
			}
			set
			{
				if ((this._LCfixedCharge != value))
				{
					this.OnLCfixedChargeChanging(value);
					this.SendPropertyChanging();
					this._LCfixedCharge = value;
					this.SendPropertyChanged("LCfixedCharge");
					this.OnLCfixedChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCvariableUnits", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCvariableUnits
		{
			get
			{
				return this._LCvariableUnits;
			}
			set
			{
				if ((this._LCvariableUnits != value))
				{
					this.OnLCvariableUnitsChanging(value);
					this.SendPropertyChanging();
					this._LCvariableUnits = value;
					this.SendPropertyChanged("LCvariableUnits");
					this.OnLCvariableUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCvariableCostPerUnit", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCvariableCostPerUnit
		{
			get
			{
				return this._LCvariableCostPerUnit;
			}
			set
			{
				if ((this._LCvariableCostPerUnit != value))
				{
					this.OnLCvariableCostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._LCvariableCostPerUnit = value;
					this.SendPropertyChanged("LCvariableCostPerUnit");
					this.OnLCvariableCostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCvariableCharge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCvariableCharge
		{
			get
			{
				return this._LCvariableCharge;
			}
			set
			{
				if ((this._LCvariableCharge != value))
				{
					this.OnLCvariableChargeChanging(value);
					this.SendPropertyChanging();
					this._LCvariableCharge = value;
					this.SendPropertyChanged("LCvariableCharge");
					this.OnLCvariableChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCmaxDemandUnits", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCmaxDemandUnits
		{
			get
			{
				return this._LCmaxDemandUnits;
			}
			set
			{
				if ((this._LCmaxDemandUnits != value))
				{
					this.OnLCmaxDemandUnitsChanging(value);
					this.SendPropertyChanging();
					this._LCmaxDemandUnits = value;
					this.SendPropertyChanged("LCmaxDemandUnits");
					this.OnLCmaxDemandUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCmaxDemandCostPerUnit", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCmaxDemandCostPerUnit
		{
			get
			{
				return this._LCmaxDemandCostPerUnit;
			}
			set
			{
				if ((this._LCmaxDemandCostPerUnit != value))
				{
					this.OnLCmaxDemandCostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._LCmaxDemandCostPerUnit = value;
					this.SendPropertyChanged("LCmaxDemandCostPerUnit");
					this.OnLCmaxDemandCostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCmaxDemandCharge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCmaxDemandCharge
		{
			get
			{
				return this._LCmaxDemandCharge;
			}
			set
			{
				if ((this._LCmaxDemandCharge != value))
				{
					this.OnLCmaxDemandChargeChanging(value);
					this.SendPropertyChanging();
					this._LCmaxDemandCharge = value;
					this.SendPropertyChanged("LCmaxDemandCharge");
					this.OnLCmaxDemandChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCassessedCapacityUnits", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCassessedCapacityUnits
		{
			get
			{
				return this._LCassessedCapacityUnits;
			}
			set
			{
				if ((this._LCassessedCapacityUnits != value))
				{
					this.OnLCassessedCapacityUnitsChanging(value);
					this.SendPropertyChanging();
					this._LCassessedCapacityUnits = value;
					this.SendPropertyChanged("LCassessedCapacityUnits");
					this.OnLCassessedCapacityUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCassessedCapacityPerUnit", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCassessedCapacityPerUnit
		{
			get
			{
				return this._LCassessedCapacityPerUnit;
			}
			set
			{
				if ((this._LCassessedCapacityPerUnit != value))
				{
					this.OnLCassessedCapacityPerUnitChanging(value);
					this.SendPropertyChanging();
					this._LCassessedCapacityPerUnit = value;
					this.SendPropertyChanged("LCassessedCapacityPerUnit");
					this.OnLCassessedCapacityPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCassessedCapacityCharge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LCassessedCapacityCharge
		{
			get
			{
				return this._LCassessedCapacityCharge;
			}
			set
			{
				if ((this._LCassessedCapacityCharge != value))
				{
					this.OnLCassessedCapacityChargeChanging(value);
					this.SendPropertyChanging();
					this._LCassessedCapacityCharge = value;
					this.SendPropertyChanged("LCassessedCapacityCharge");
					this.OnLCassessedCapacityChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday00_04_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday00_04_Units
		{
			get
			{
				return this._Weekday00_04_Units;
			}
			set
			{
				if ((this._Weekday00_04_Units != value))
				{
					this.OnWeekday00_04_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekday00_04_Units = value;
					this.SendPropertyChanged("Weekday00_04_Units");
					this.OnWeekday00_04_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday04_08_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday04_08_Units
		{
			get
			{
				return this._Weekday04_08_Units;
			}
			set
			{
				if ((this._Weekday04_08_Units != value))
				{
					this.OnWeekday04_08_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekday04_08_Units = value;
					this.SendPropertyChanged("Weekday04_08_Units");
					this.OnWeekday04_08_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday08_12_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday08_12_Units
		{
			get
			{
				return this._Weekday08_12_Units;
			}
			set
			{
				if ((this._Weekday08_12_Units != value))
				{
					this.OnWeekday08_12_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekday08_12_Units = value;
					this.SendPropertyChanged("Weekday08_12_Units");
					this.OnWeekday08_12_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday12_16_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday12_16_Units
		{
			get
			{
				return this._Weekday12_16_Units;
			}
			set
			{
				if ((this._Weekday12_16_Units != value))
				{
					this.OnWeekday12_16_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekday12_16_Units = value;
					this.SendPropertyChanged("Weekday12_16_Units");
					this.OnWeekday12_16_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday16_20_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday16_20_Units
		{
			get
			{
				return this._Weekday16_20_Units;
			}
			set
			{
				if ((this._Weekday16_20_Units != value))
				{
					this.OnWeekday16_20_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekday16_20_Units = value;
					this.SendPropertyChanged("Weekday16_20_Units");
					this.OnWeekday16_20_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday20_24_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday20_24_Units
		{
			get
			{
				return this._Weekday20_24_Units;
			}
			set
			{
				if ((this._Weekday20_24_Units != value))
				{
					this.OnWeekday20_24_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekday20_24_Units = value;
					this.SendPropertyChanged("Weekday20_24_Units");
					this.OnWeekday20_24_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend00_04_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend00_04_Units
		{
			get
			{
				return this._Weekend00_04_Units;
			}
			set
			{
				if ((this._Weekend00_04_Units != value))
				{
					this.OnWeekend00_04_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekend00_04_Units = value;
					this.SendPropertyChanged("Weekend00_04_Units");
					this.OnWeekend00_04_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend04_08_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend04_08_Units
		{
			get
			{
				return this._Weekend04_08_Units;
			}
			set
			{
				if ((this._Weekend04_08_Units != value))
				{
					this.OnWeekend04_08_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekend04_08_Units = value;
					this.SendPropertyChanged("Weekend04_08_Units");
					this.OnWeekend04_08_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend08_12_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend08_12_Units
		{
			get
			{
				return this._Weekend08_12_Units;
			}
			set
			{
				if ((this._Weekend08_12_Units != value))
				{
					this.OnWeekend08_12_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekend08_12_Units = value;
					this.SendPropertyChanged("Weekend08_12_Units");
					this.OnWeekend08_12_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend12_16_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend12_16_Units
		{
			get
			{
				return this._Weekend12_16_Units;
			}
			set
			{
				if ((this._Weekend12_16_Units != value))
				{
					this.OnWeekend12_16_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekend12_16_Units = value;
					this.SendPropertyChanged("Weekend12_16_Units");
					this.OnWeekend12_16_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend16_20_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend16_20_Units
		{
			get
			{
				return this._Weekend16_20_Units;
			}
			set
			{
				if ((this._Weekend16_20_Units != value))
				{
					this.OnWeekend16_20_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekend16_20_Units = value;
					this.SendPropertyChanged("Weekend16_20_Units");
					this.OnWeekend16_20_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend20_24_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend20_24_Units
		{
			get
			{
				return this._Weekend20_24_Units;
			}
			set
			{
				if ((this._Weekend20_24_Units != value))
				{
					this.OnWeekend20_24_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Weekend20_24_Units = value;
					this.SendPropertyChanged("Weekend20_24_Units");
					this.OnWeekend20_24_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday00_04_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday00_04_Losses
		{
			get
			{
				return this._Weekday00_04_Losses;
			}
			set
			{
				if ((this._Weekday00_04_Losses != value))
				{
					this.OnWeekday00_04_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekday00_04_Losses = value;
					this.SendPropertyChanged("Weekday00_04_Losses");
					this.OnWeekday00_04_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday04_08_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday04_08_Losses
		{
			get
			{
				return this._Weekday04_08_Losses;
			}
			set
			{
				if ((this._Weekday04_08_Losses != value))
				{
					this.OnWeekday04_08_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekday04_08_Losses = value;
					this.SendPropertyChanged("Weekday04_08_Losses");
					this.OnWeekday04_08_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday08_12_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday08_12_Losses
		{
			get
			{
				return this._Weekday08_12_Losses;
			}
			set
			{
				if ((this._Weekday08_12_Losses != value))
				{
					this.OnWeekday08_12_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekday08_12_Losses = value;
					this.SendPropertyChanged("Weekday08_12_Losses");
					this.OnWeekday08_12_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday12_16_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday12_16_Losses
		{
			get
			{
				return this._Weekday12_16_Losses;
			}
			set
			{
				if ((this._Weekday12_16_Losses != value))
				{
					this.OnWeekday12_16_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekday12_16_Losses = value;
					this.SendPropertyChanged("Weekday12_16_Losses");
					this.OnWeekday12_16_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday16_20_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday16_20_Losses
		{
			get
			{
				return this._Weekday16_20_Losses;
			}
			set
			{
				if ((this._Weekday16_20_Losses != value))
				{
					this.OnWeekday16_20_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekday16_20_Losses = value;
					this.SendPropertyChanged("Weekday16_20_Losses");
					this.OnWeekday16_20_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday20_24_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday20_24_Losses
		{
			get
			{
				return this._Weekday20_24_Losses;
			}
			set
			{
				if ((this._Weekday20_24_Losses != value))
				{
					this.OnWeekday20_24_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekday20_24_Losses = value;
					this.SendPropertyChanged("Weekday20_24_Losses");
					this.OnWeekday20_24_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend00_04_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend00_04_Losses
		{
			get
			{
				return this._Weekend00_04_Losses;
			}
			set
			{
				if ((this._Weekend00_04_Losses != value))
				{
					this.OnWeekend00_04_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekend00_04_Losses = value;
					this.SendPropertyChanged("Weekend00_04_Losses");
					this.OnWeekend00_04_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend04_08_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend04_08_Losses
		{
			get
			{
				return this._Weekend04_08_Losses;
			}
			set
			{
				if ((this._Weekend04_08_Losses != value))
				{
					this.OnWeekend04_08_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekend04_08_Losses = value;
					this.SendPropertyChanged("Weekend04_08_Losses");
					this.OnWeekend04_08_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend08_12_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend08_12_Losses
		{
			get
			{
				return this._Weekend08_12_Losses;
			}
			set
			{
				if ((this._Weekend08_12_Losses != value))
				{
					this.OnWeekend08_12_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekend08_12_Losses = value;
					this.SendPropertyChanged("Weekend08_12_Losses");
					this.OnWeekend08_12_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend12_16_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend12_16_Losses
		{
			get
			{
				return this._Weekend12_16_Losses;
			}
			set
			{
				if ((this._Weekend12_16_Losses != value))
				{
					this.OnWeekend12_16_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekend12_16_Losses = value;
					this.SendPropertyChanged("Weekend12_16_Losses");
					this.OnWeekend12_16_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend16_20_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend16_20_Losses
		{
			get
			{
				return this._Weekend16_20_Losses;
			}
			set
			{
				if ((this._Weekend16_20_Losses != value))
				{
					this.OnWeekend16_20_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekend16_20_Losses = value;
					this.SendPropertyChanged("Weekend16_20_Losses");
					this.OnWeekend16_20_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend20_24_Losses", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend20_24_Losses
		{
			get
			{
				return this._Weekend20_24_Losses;
			}
			set
			{
				if ((this._Weekend20_24_Losses != value))
				{
					this.OnWeekend20_24_LossesChanging(value);
					this.SendPropertyChanging();
					this._Weekend20_24_Losses = value;
					this.SendPropertyChanged("Weekend20_24_Losses");
					this.OnWeekend20_24_LossesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday00_04_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekday00_04_CostPerUnit
		{
			get
			{
				return this._Weekday00_04_CostPerUnit;
			}
			set
			{
				if ((this._Weekday00_04_CostPerUnit != value))
				{
					this.OnWeekday00_04_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekday00_04_CostPerUnit = value;
					this.SendPropertyChanged("Weekday00_04_CostPerUnit");
					this.OnWeekday00_04_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday04_08_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekday04_08_CostPerUnit
		{
			get
			{
				return this._Weekday04_08_CostPerUnit;
			}
			set
			{
				if ((this._Weekday04_08_CostPerUnit != value))
				{
					this.OnWeekday04_08_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekday04_08_CostPerUnit = value;
					this.SendPropertyChanged("Weekday04_08_CostPerUnit");
					this.OnWeekday04_08_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday08_12_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekday08_12_CostPerUnit
		{
			get
			{
				return this._Weekday08_12_CostPerUnit;
			}
			set
			{
				if ((this._Weekday08_12_CostPerUnit != value))
				{
					this.OnWeekday08_12_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekday08_12_CostPerUnit = value;
					this.SendPropertyChanged("Weekday08_12_CostPerUnit");
					this.OnWeekday08_12_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday12_16_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekday12_16_CostPerUnit
		{
			get
			{
				return this._Weekday12_16_CostPerUnit;
			}
			set
			{
				if ((this._Weekday12_16_CostPerUnit != value))
				{
					this.OnWeekday12_16_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekday12_16_CostPerUnit = value;
					this.SendPropertyChanged("Weekday12_16_CostPerUnit");
					this.OnWeekday12_16_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday16_20_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekday16_20_CostPerUnit
		{
			get
			{
				return this._Weekday16_20_CostPerUnit;
			}
			set
			{
				if ((this._Weekday16_20_CostPerUnit != value))
				{
					this.OnWeekday16_20_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekday16_20_CostPerUnit = value;
					this.SendPropertyChanged("Weekday16_20_CostPerUnit");
					this.OnWeekday16_20_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday20_24_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekday20_24_CostPerUnit
		{
			get
			{
				return this._Weekday20_24_CostPerUnit;
			}
			set
			{
				if ((this._Weekday20_24_CostPerUnit != value))
				{
					this.OnWeekday20_24_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekday20_24_CostPerUnit = value;
					this.SendPropertyChanged("Weekday20_24_CostPerUnit");
					this.OnWeekday20_24_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend00_04_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekend00_04_CostPerUnit
		{
			get
			{
				return this._Weekend00_04_CostPerUnit;
			}
			set
			{
				if ((this._Weekend00_04_CostPerUnit != value))
				{
					this.OnWeekend00_04_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekend00_04_CostPerUnit = value;
					this.SendPropertyChanged("Weekend00_04_CostPerUnit");
					this.OnWeekend00_04_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend04_08_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekend04_08_CostPerUnit
		{
			get
			{
				return this._Weekend04_08_CostPerUnit;
			}
			set
			{
				if ((this._Weekend04_08_CostPerUnit != value))
				{
					this.OnWeekend04_08_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekend04_08_CostPerUnit = value;
					this.SendPropertyChanged("Weekend04_08_CostPerUnit");
					this.OnWeekend04_08_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend08_12_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekend08_12_CostPerUnit
		{
			get
			{
				return this._Weekend08_12_CostPerUnit;
			}
			set
			{
				if ((this._Weekend08_12_CostPerUnit != value))
				{
					this.OnWeekend08_12_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekend08_12_CostPerUnit = value;
					this.SendPropertyChanged("Weekend08_12_CostPerUnit");
					this.OnWeekend08_12_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend12_16_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekend12_16_CostPerUnit
		{
			get
			{
				return this._Weekend12_16_CostPerUnit;
			}
			set
			{
				if ((this._Weekend12_16_CostPerUnit != value))
				{
					this.OnWeekend12_16_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekend12_16_CostPerUnit = value;
					this.SendPropertyChanged("Weekend12_16_CostPerUnit");
					this.OnWeekend12_16_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend16_20_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekend16_20_CostPerUnit
		{
			get
			{
				return this._Weekend16_20_CostPerUnit;
			}
			set
			{
				if ((this._Weekend16_20_CostPerUnit != value))
				{
					this.OnWeekend16_20_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekend16_20_CostPerUnit = value;
					this.SendPropertyChanged("Weekend16_20_CostPerUnit");
					this.OnWeekend16_20_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend20_24_CostPerUnit", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Weekend20_24_CostPerUnit
		{
			get
			{
				return this._Weekend20_24_CostPerUnit;
			}
			set
			{
				if ((this._Weekend20_24_CostPerUnit != value))
				{
					this.OnWeekend20_24_CostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._Weekend20_24_CostPerUnit = value;
					this.SendPropertyChanged("Weekend20_24_CostPerUnit");
					this.OnWeekend20_24_CostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromDate", DbType="Date")]
		public System.Nullable<System.DateTime> FromDate
		{
			get
			{
				return this._FromDate;
			}
			set
			{
				if ((this._FromDate != value))
				{
					this.OnFromDateChanging(value);
					this.SendPropertyChanging();
					this._FromDate = value;
					this.SendPropertyChanged("FromDate");
					this.OnFromDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToDate", DbType="Date")]
		public System.Nullable<System.DateTime> ToDate
		{
			get
			{
				return this._ToDate;
			}
			set
			{
				if ((this._ToDate != value))
				{
					this.OnToDateChanging(value);
					this.SendPropertyChanging();
					this._ToDate = value;
					this.SendPropertyChanged("ToDate");
					this.OnToDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedMatches", DbType="Int")]
		public System.Nullable<int> FailedMatches
		{
			get
			{
				return this._FailedMatches;
			}
			set
			{
				if ((this._FailedMatches != value))
				{
					this.OnFailedMatchesChanging(value);
					this.SendPropertyChanging();
					this._FailedMatches = value;
					this.SendPropertyChanged("FailedMatches");
					this.OnFailedMatchesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScannedFileName", DbType="NVarChar(30)")]
		public string ScannedFileName
		{
			get
			{
				return this._ScannedFileName;
			}
			set
			{
				if ((this._ScannedFileName != value))
				{
					this.OnScannedFileNameChanging(value);
					this.SendPropertyChanging();
					this._ScannedFileName = value;
					this.SendPropertyChanged("ScannedFileName");
					this.OnScannedFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScanDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ScanDate
		{
			get
			{
				return this._ScanDate;
			}
			set
			{
				if ((this._ScanDate != value))
				{
					this.OnScanDateChanging(value);
					this.SendPropertyChanging();
					this._ScanDate = value;
					this.SendPropertyChanged("ScanDate");
					this.OnScanDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedValidations", DbType="Int")]
		public System.Nullable<int> FailedValidations
		{
			get
			{
				return this._FailedValidations;
			}
			set
			{
				if ((this._FailedValidations != value))
				{
					this.OnFailedValidationsChanging(value);
					this.SendPropertyChanging();
					this._FailedValidations = value;
					this.SendPropertyChanged("FailedValidations");
					this.OnFailedValidationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday00_04_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday00_04_Charge
		{
			get
			{
				return this._Weekday00_04_Charge;
			}
			set
			{
				if ((this._Weekday00_04_Charge != value))
				{
					this.OnWeekday00_04_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekday00_04_Charge = value;
					this.SendPropertyChanged("Weekday00_04_Charge");
					this.OnWeekday00_04_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday04_08_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday04_08_Charge
		{
			get
			{
				return this._Weekday04_08_Charge;
			}
			set
			{
				if ((this._Weekday04_08_Charge != value))
				{
					this.OnWeekday04_08_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekday04_08_Charge = value;
					this.SendPropertyChanged("Weekday04_08_Charge");
					this.OnWeekday04_08_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday08_12_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday08_12_Charge
		{
			get
			{
				return this._Weekday08_12_Charge;
			}
			set
			{
				if ((this._Weekday08_12_Charge != value))
				{
					this.OnWeekday08_12_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekday08_12_Charge = value;
					this.SendPropertyChanged("Weekday08_12_Charge");
					this.OnWeekday08_12_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday12_16_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday12_16_Charge
		{
			get
			{
				return this._Weekday12_16_Charge;
			}
			set
			{
				if ((this._Weekday12_16_Charge != value))
				{
					this.OnWeekday12_16_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekday12_16_Charge = value;
					this.SendPropertyChanged("Weekday12_16_Charge");
					this.OnWeekday12_16_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday16_20_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday16_20_Charge
		{
			get
			{
				return this._Weekday16_20_Charge;
			}
			set
			{
				if ((this._Weekday16_20_Charge != value))
				{
					this.OnWeekday16_20_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekday16_20_Charge = value;
					this.SendPropertyChanged("Weekday16_20_Charge");
					this.OnWeekday16_20_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekday20_24_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekday20_24_Charge
		{
			get
			{
				return this._Weekday20_24_Charge;
			}
			set
			{
				if ((this._Weekday20_24_Charge != value))
				{
					this.OnWeekday20_24_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekday20_24_Charge = value;
					this.SendPropertyChanged("Weekday20_24_Charge");
					this.OnWeekday20_24_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend00_04_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend00_04_Charge
		{
			get
			{
				return this._Weekend00_04_Charge;
			}
			set
			{
				if ((this._Weekend00_04_Charge != value))
				{
					this.OnWeekend00_04_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekend00_04_Charge = value;
					this.SendPropertyChanged("Weekend00_04_Charge");
					this.OnWeekend00_04_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend04_08_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend04_08_Charge
		{
			get
			{
				return this._Weekend04_08_Charge;
			}
			set
			{
				if ((this._Weekend04_08_Charge != value))
				{
					this.OnWeekend04_08_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekend04_08_Charge = value;
					this.SendPropertyChanged("Weekend04_08_Charge");
					this.OnWeekend04_08_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend08_12_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend08_12_Charge
		{
			get
			{
				return this._Weekend08_12_Charge;
			}
			set
			{
				if ((this._Weekend08_12_Charge != value))
				{
					this.OnWeekend08_12_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekend08_12_Charge = value;
					this.SendPropertyChanged("Weekend08_12_Charge");
					this.OnWeekend08_12_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend12_16_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend12_16_Charge
		{
			get
			{
				return this._Weekend12_16_Charge;
			}
			set
			{
				if ((this._Weekend12_16_Charge != value))
				{
					this.OnWeekend12_16_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekend12_16_Charge = value;
					this.SendPropertyChanged("Weekend12_16_Charge");
					this.OnWeekend12_16_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend16_20_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend16_20_Charge
		{
			get
			{
				return this._Weekend16_20_Charge;
			}
			set
			{
				if ((this._Weekend16_20_Charge != value))
				{
					this.OnWeekend16_20_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekend16_20_Charge = value;
					this.SendPropertyChanged("Weekend16_20_Charge");
					this.OnWeekend16_20_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weekend20_24_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Weekend20_24_Charge
		{
			get
			{
				return this._Weekend20_24_Charge;
			}
			set
			{
				if ((this._Weekend20_24_Charge != value))
				{
					this.OnWeekend20_24_ChargeChanging(value);
					this.SendPropertyChanging();
					this._Weekend20_24_Charge = value;
					this.SendPropertyChanged("Weekend20_24_Charge");
					this.OnWeekend20_24_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCharge_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AdminCharge_Units
		{
			get
			{
				return this._AdminCharge_Units;
			}
			set
			{
				if ((this._AdminCharge_Units != value))
				{
					this.OnAdminCharge_UnitsChanging(value);
					this.SendPropertyChanging();
					this._AdminCharge_Units = value;
					this.SendPropertyChanged("AdminCharge_Units");
					this.OnAdminCharge_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCharge_Rate", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AdminCharge_Rate
		{
			get
			{
				return this._AdminCharge_Rate;
			}
			set
			{
				if ((this._AdminCharge_Rate != value))
				{
					this.OnAdminCharge_RateChanging(value);
					this.SendPropertyChanging();
					this._AdminCharge_Rate = value;
					this.SendPropertyChanged("AdminCharge_Rate");
					this.OnAdminCharge_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCharge_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AdminCharge_Charge
		{
			get
			{
				return this._AdminCharge_Charge;
			}
			set
			{
				if ((this._AdminCharge_Charge != value))
				{
					this.OnAdminCharge_ChargeChanging(value);
					this.SendPropertyChanging();
					this._AdminCharge_Charge = value;
					this.SendPropertyChanged("AdminCharge_Charge");
					this.OnAdminCharge_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECLevies_Units", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ECLevies_Units
		{
			get
			{
				return this._ECLevies_Units;
			}
			set
			{
				if ((this._ECLevies_Units != value))
				{
					this.OnECLevies_UnitsChanging(value);
					this.SendPropertyChanging();
					this._ECLevies_Units = value;
					this.SendPropertyChanged("ECLevies_Units");
					this.OnECLevies_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECLevies_Rate", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> ECLevies_Rate
		{
			get
			{
				return this._ECLevies_Rate;
			}
			set
			{
				if ((this._ECLevies_Rate != value))
				{
					this.OnECLevies_RateChanging(value);
					this.SendPropertyChanging();
					this._ECLevies_Rate = value;
					this.SendPropertyChanged("ECLevies_Rate");
					this.OnECLevies_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECLevies_Charge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ECLevies_Charge
		{
			get
			{
				return this._ECLevies_Charge;
			}
			set
			{
				if ((this._ECLevies_Charge != value))
				{
					this.OnECLevies_ChargeChanging(value);
					this.SendPropertyChanging();
					this._ECLevies_Charge = value;
					this.SendPropertyChanged("ECLevies_Charge");
					this.OnECLevies_ChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCharge", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TotalCharge
		{
			get
			{
				return this._TotalCharge;
			}
			set
			{
				if ((this._TotalCharge != value))
				{
					this.OnTotalChargeChanging(value);
					this.SendPropertyChanging();
					this._TotalCharge = value;
					this.SendPropertyChanged("TotalCharge");
					this.OnTotalChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedValidationRecords", DbType="NVarChar(250)")]
		public string FailedValidationRecords
		{
			get
			{
				return this._FailedValidationRecords;
			}
			set
			{
				if ((this._FailedValidationRecords != value))
				{
					this.OnFailedValidationRecordsChanging(value);
					this.SendPropertyChanging();
					this._FailedValidationRecords = value;
					this.SendPropertyChanged("FailedValidationRecords");
					this.OnFailedValidationRecordsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
